"""
Django settings for trainme project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# llm_engine/ lives one level up (repo root), as a sibling of the Django project
# dir (BASE_DIR) rather than inside it, so it must be added to sys.path manually.
REPO_ROOT = BASE_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vjph!cu(1=)q&q#iko4#an7*3fe5)q*xxrnum3b9#e52f&=10s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trainme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trainme.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# Media files configuration for transcriptions and audio files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create necessary directories for transcriptions and audio
import os
TRANSCRIPTION_DIR = MEDIA_ROOT / 'text_transcription'
AUDIO_DIR = MEDIA_ROOT / 'wavs'

os.makedirs(TRANSCRIPTION_DIR, exist_ok=True)
os.makedirs(AUDIO_DIR, exist_ok=True)

# Base64-encoded audio in /speech/ requests can exceed Django's 2.5MB default
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# Persona teacher/student agents (llm_engine/) — local Ollama models
PERSONA_DIR = MEDIA_ROOT / 'personas'
os.makedirs(PERSONA_DIR, exist_ok=True)

OLLAMA_MODEL = "qwen3:8b"
OLLAMA_EMBED_MODEL = "nomic-embed-text"
PERSONA_TRAIN_MAX_ITERATIONS = 5
PERSONA_TRAIN_CONVERGENCE_EPS = 0.02

# Voice-cloning reference clips (tts_engine/) — curated per user, not media/,
# since it's raw voice biometric data rather than app-served media.
TTS_VOICES_DIR = REPO_ROOT / 'tts_engine' / 'voices'
os.makedirs(TTS_VOICES_DIR, exist_ok=True)
TTS_VOICE_MAX_CLIPS = 3

# Real XTTS GPT fine-tuning (tts_engine/finetune.py) — heavy, GPU-bound, only
# ever triggered manually via `manage.py finetune_voice` (see plan/README).
TTS_FINETUNE_DIR = REPO_ROOT / 'tts_engine' / 'finetune_runs'
os.makedirs(TTS_FINETUNE_DIR, exist_ok=True)
TTS_FINETUNE_MIN_SECONDS = 120
TTS_FINETUNE_LANGUAGE = "pl"
TTS_FINETUNE_EPOCHS = 10
TTS_FINETUNE_BATCH_SIZE = 4

LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL           = '/login/'

