# Generated by Django 4.2.8 on 2026-04-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_id', models.CharField(help_text='Unique identifier for the transcription session', max_length=255, unique=True)),
                ('full_text', models.TextField(blank=True, help_text='Full transcription text', null=True)),
                ('sentence_count', models.IntegerField(default=0, help_text='Number of sentences in the transcription')),
                ('audio_file_path', models.CharField(blank=True, help_text='Path to the WAV audio file', max_length=500, null=True)),
                ('transcription_dir_path', models.CharField(blank=True, help_text='Path to the transcription directory', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transcription Session',
                'verbose_name_plural': 'Transcription Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_number', models.IntegerField(help_text='Sentence sequence number within the session')),
                ('text', models.TextField(help_text='The sentence text')),
                ('file_path', models.CharField(blank=True, help_text='Path to the sentence text file', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='home.transcriptionsession')),
            ],
            options={
                'verbose_name': 'Transcription Sentence',
                'verbose_name_plural': 'Transcription Sentences',
                'ordering': ['sentence_number'],
                'unique_together': {('session', 'sentence_number')},
            },
        ),
    ]
